// payload/modules/medialibrarypro/resources/js/media-library-pro-vue2/src/Thumb.vue
<template>
    <div class="media-library-thumb" dusk="thumb">
        <img
            v-if="!!imgProps.src && !imageErrored"
            v-bind="imgProps"
            class="media-library-thumb-img"
            @error="imageErrored = true"
        />

        <span v-else class="media-library-thumb-extension">
            <span class="media-library-thumb-extension-truncate">{{ imgProps.extension }}</span>
        </span>

        <uploader
            v-bind="$attrs"
            :validation-rules="validationRules"
            :add="false"
            :multiple="false"
            :upload-info="uploadInfo"
            @dropped="$emit('replaced', $event.dataTransfer.files[0])"
            @changed="$emit('replaced', $event.target.files[0])"
        />
    </div>
</template>

<script>
import Uploader from './Uploader.vue';

export default {
    props: {
        uploadInfo: { required: true, type: Object },
        validationRules: { required: false, type: Object },
        imgProps: { required: true, type: Object },
    },

    emits: ['replaced'],

    components: { Uploader },

    data: function () {
        return { imageErrored: false, oldImgSrc: this.imgProps.src };
    },

    watch: {
        imgProps: {
            deep: true,
            immediate: true,
            handler: function (val) {
                if (this.oldImgSrc != val.src) {
                    this.imageErrored = false;
                }
            },
        },
    },
};
</script>

// payload/modules/medialibrarypro/resources/js/media-library-pro-react/src/Thumb.tsx
import * as React from 'react';
import { MediaLibrary } from '@spatie/media-library-pro-core/dist/types';
import Uploader from './Uploader';

type Props = {
    uploadInfo: MediaLibrary.MediaObject['upload'];
    validationRules?: Partial<MediaLibrary.Config['validationRules']>;
    imgProps: {
        src: string | undefined;
        alt: string;
        extension: string | undefined;
    };
    onReplace: (file: File) => void;
};

export default function Thumb({ uploadInfo, validationRules, imgProps, onReplace, ...props }: Props) {
    const [imageErrored, setImageErrored] = React.useState(false);

    const oldImgSrc = React.useRef(imgProps.src);

    React.useEffect(() => {
        if (oldImgSrc.current != imgProps.src) {
            setImageErrored(false);
        }
    }, [imgProps.src]);

    return (
        <>
            <div className="media-library-thumb" {...{ dusk: 'thumb' }}>
                {!!imgProps.src && !imageErrored ? (
                    <img className="media-library-thumb-img" onError={() => setImageErrored(true)} {...imgProps} />
                ) : (
                    <span className="media-library-thumb-extension">
                        <span className="media-library-thumb-extension-truncate">{imgProps.extension}</span>
                    </span>
                )}
                <Uploader
                    validationRules={validationRules}
                    onDrop={(event: React.DragEvent) => onReplace(event.dataTransfer.files[0])}
                    onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
                        onReplace((event.target.files as FileList)[0])
                    }
                    add={false}
                    multiple={false}
                    uploadInfo={uploadInfo}
                    {...props}
                />
            </div>
        </>
    );
}
