// payload/modules/medialibrarypro/resources/js/media-library-pro-react-collection/src/MediaLibraryCollection.tsx
import * as React from 'react';
import {
    useMediaLibrary,
    HiddenFields,
    Thumb,
    ListErrors,
    ItemErrors,
    useDragula,
    Icons,
    Uploader,
    Icon,
} from '@spatie/media-library-pro-react';
import { MediaLibrary as MediaLibraryClass } from '@spatie/media-library-pro-core';
import { MediaLibrary } from '@spatie/media-library-pro-core/dist/types';

type Props = {
    name: string;
    initialValue?: MediaLibrary.Options['initialValue'];
    routePrefix?: string;
    translations?: MediaLibrary.Options['translations'];
    validationRules?: Partial<MediaLibraryClass['config']['validationRules']>;
    validationErrors?: { [key: string]: Array<string> } | Array<never>;
    sortable?: boolean;
    maxItems?: number;
    maxSizeForPreviewInBytes?: number;
    vapor?: MediaLibrary.Config['vapor'];
    vaporSignedStorageUrl?: MediaLibrary.Config['vaporSignedStorageUrl'];
    uploadDomain?: MediaLibrary.Config['uploadDomain'];
    withCredentials?: MediaLibrary.Config['withCredentials'];
    headers?: MediaLibrary.Config['headers'];
    fileTypeHelpText?: string;
    setMediaLibrary?: (mediaLibrary: MediaLibraryClass) => void;
    beforeUpload?: MediaLibraryClass['config']['beforeUpload'];
    afterUpload?: MediaLibraryClass['config']['afterUpload'];
    onChange?: (media: { [uuid: string]: MediaLibrary.MediaAttributes }) => void;
    onIsReadyToSubmitChange?: (isReadyToSubmit: boolean) => void;
    propertiesView?: (helpers: { object: MediaLibrary.MediaObject }) => React.ReactNode;
    fieldsView?: (helpers: {
        object: MediaLibrary.MediaObject;
        getCustomPropertyInputProps: (
            propertyName: string
        ) => { value: any; onChange: (event: React.ChangeEvent<HTMLInputElement>) => void };
        getCustomPropertyInputErrors: (
            propertyName: string
        ) => ReturnType<MediaLibraryClass['getCustomPropertyInputErrors']>;

        getNameInputProps: () => {
            value: any;
            onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
        };
        getNameInputErrors: () => Array<string>;
    }) => React.ReactNode;
};

export default function MediaLibraryCollection({
    name,
    initialValue = [],
    translations = {},
    validationRules,
    validationErrors = {},
    routePrefix,
    sortable = true,
    maxItems,
    maxSizeForPreviewInBytes,
    vapor,
    vaporSignedStorageUrl,
    uploadDomain,
    withCredentials,
    headers,
    fileTypeHelpText,
    setMediaLibrary,
    propertiesView = DefaultPropertiesView,
    fieldsView = DefaultFieldsView,
    beforeUpload = () => {},
    afterUpload = () => {},
    onChange = () => {},
    onIsReadyToSubmitChange = () => {},
}: Props) {
    const {
        mediaLibrary,
        state,
        getImgProps,
        getNameInputProps,
        getNameInputErrors,
        getCustomPropertyInputProps,
        getCustomPropertyInputErrors,
        getFileInputProps,
        getDropZoneProps,
        removeMedia,
        setOrder,
        replaceMedia,
        getErrors,
        clearObjectErrors,
        clearInvalidMedia,
        isReadyToSubmit,
    } = useMediaLibrary({
        name,
        initialValue: initialValue,
        validationErrors: Array.isArray(validationErrors) ? {} : validationErrors,
        routePrefix,
        validationRules,
        translations,
        maxItems,
        maxSizeForPreviewInBytes,
        vapor,
        vaporSignedStorageUrl,
        uploadDomain,
        withCredentials,
        headers,
        beforeUpload,
        afterUpload,
        onChange,
    });

    React.useEffect(() => {
        onIsReadyToSubmitChange(isReadyToSubmit);
    }, [isReadyToSubmit]);

    React.useEffect(() => {
        if (setMediaLibrary && mediaLibrary) {
            setMediaLibrary(mediaLibrary);
        }
    }, [setMediaLibrary, mediaLibrary]);

    const { dragulaDecorator, drake } = useDragula('dragula-handle');

    React.useEffect(() => {
        if (drake) {
            drake.on('dragend', (e) => {
                setOrder(
                    Array.from(e.parentElement?.children || []).map((element) => {
                        return element.getAttribute('data-media-library-uuid') as string;
                    })
                );
            });
        }
    }, [drake]);

    return (
        <>
            <Icons />
            <div
                className={`media-library media-library-multiple ${
                    state.media.length == 0 ? 'media-library-empty' : 'media-library-filled'
                } ${sortable && 'media-library-sortable'}`}
            >
                <ListErrors
                    invalidMedia={state.invalidMedia}
                    topLevelErrors={Array.isArray(validationErrors) ? undefined : validationErrors[name]}
                    onClear={clearInvalidMedia}
                />

                {state.media?.length > 0 && (
                    <div className="media-library-items" ref={sortable ? dragulaDecorator : undefined}>
                        {state.media.map((object: MediaLibrary.MediaObject) => {
                            const objectErrors = getErrors(object);
                            return (
                                <div
                                    className="media-library-item media-library-item-row"
                                    key={object.attributes.uuid}
                                    data-media-library-uuid={object.attributes.uuid}
                                >
                                    {sortable && (
                                        <div className="dragula-handle media-library-row-drag">
                                            {sortable && <Icon icon="drag" />}
                                        </div>
                                    )}

                                    <Thumb
                                        uploadInfo={object.upload}
                                        validationRules={validationRules}
                                        imgProps={getImgProps(object)}
                                        onReplace={(file: File) => replaceMedia(object, file)}
                                    />

                                    {!!objectErrors.length ? (
                                        <ItemErrors
                                            objectErrors={objectErrors}
                                            onBack={() => clearObjectErrors(object)}
                                        />
                                    ) : (
                                        <>
                                            {propertiesView({ object })}

                                            {fieldsView({
                                                object,
                                                getCustomPropertyInputProps: (propertyName: string) =>
                                                    getCustomPropertyInputProps(object, propertyName),
                                                getCustomPropertyInputErrors: (propertyName: string) =>
                                                    getCustomPropertyInputErrors(object, propertyName),
                                                getNameInputProps: () => getNameInputProps(object),
                                                getNameInputErrors: () => getNameInputErrors(object),
                                            })}
                                        </>
                                    )}

                                    <div
                                        className="media-library-row-remove"
                                        onClick={() => removeMedia(object)}
                                        {...{ dusk: 'remove' }}
                                    >
                                        <Icon icon="remove" />
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                )}

                <HiddenFields name={name} mediaState={state.media} />

                <div
                    className={
                        !maxItems || state.media.length < maxItems ? 'media-library-uploader' : 'media-library-hidden'
                    }
                >
                    <Uploader
                        {...getDropZoneProps()}
                        {...getFileInputProps()}
                        add
                        multiple
                        fileTypeHelpText={fileTypeHelpText}
                    />
                </div>
            </div>
        </>
    );
}

type DefaultPropertiesViewProps = {
    object: MediaLibrary.MediaObject;
};

function DefaultPropertiesView({ object }: DefaultPropertiesViewProps) {
    return (
        <div className="media-library-properties media-library-properties-fixed">
            {object.attributes.extension && (
                <div className="media-library-property">{object.attributes.extension.toUpperCase()}</div>
            )}
            {object.attributes.size && (
                <div className="media-library-property">{(object.attributes.size / 1024).toFixed(2)} KB</div>
            )}
            {object.attributes.original_url && (
                <div className="media-library-property">
                    <a
                        href={object.attributes.original_url}
                        download
                        target="_blank"
                        className="media-library-text-link"
                    >
                        {window.mediaLibraryTranslations.download}
                    </a>
                </div>
            )}
        </div>
    );
}

type DefaultFieldsViewProps = {
    object: MediaLibrary.MediaObject;
    getNameInputProps: () => {
        value: any;
        onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    };
    getNameInputErrors: () => Array<string>;
    getCustomPropertyInputProps: (
        propertyName: string
    ) => {
        value: any;
        onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    };
    getCustomPropertyInputErrors: (propertyName: string) => Array<string>;
};

function DefaultFieldsView({ getNameInputProps, getNameInputErrors }: DefaultFieldsViewProps) {
    return (
        <div className="media-library-properties">
            <div className="media-library-field">
                <label className="media-library-label">{window.mediaLibraryTranslations.name}</label>
                <input
                    className="media-library-input"
                    {...getNameInputProps()}
                    {...{ dusk: 'media-library-field-name' }}
                />
                {getNameInputErrors().map((error) => (
                    <p key={error} className="media-library-field-error">
                        {error}
                    </p>
                ))}
            </div>
        </div>
    );
}

// payload/modules/medialibrarypro/resources/js/media-library-pro-vue3-collection/src/MediaLibraryCollection.vue
<template>
    <media-library-renderless
        ref="mediaLibraryRenderless"
        :initial-value="initialValue"
        :validation-errors="validationErrors"
        :route-prefix="routePrefix"
        :validation-rules="validationRules"
        :translations="translations"
        :before-upload="beforeUpload"
        :after-upload="afterUpload"
        :name="name"
        :max-items="computedMaxItems"
        :max-size-for-preview-in-bytes="maxSizeForPreviewInBytes"
        :vapor="vapor"
        :vapor-signed-storage-url="vaporSignedStorageUrl"
        :upload-domain="uploadDomain"
        :with-credentials="withCredentials"
        :headers="headers"
        @changed="$emit('change', $event)"
        @is-ready-to-submit-change="$emit('is-ready-to-submit-change', $event)"
        @has-uploads-in-progress-change="$emit('has-uploads-in-progress-change', $event)"
        v-slot="{
            state,
            removeMedia,
            getImgProps,
            getCustomPropertyInputProps,
            getCustomPropertyInputListeners,
            getCustomPropertyInputErrors,
            getNameInputProps,
            getNameInputListeners,
            getNameInputErrors,
            getDropZoneProps,
            getDropZoneListeners,
            getFileInputProps,
            getFileInputListeners,
            replaceMedia,
            getErrors,
            clearObjectErrors,
            clearInvalidMedia,
        }"
    >
        <icons />

        <div
            :class="`media-library media-library-multiple ${
                state.media.length == 0 ? 'media-library-empty' : 'media-library-filled'
            } ${sortable && 'media-library-sortable'}`"
        >
            <list-errors
                :invalid-media="state.invalidMedia"
                :top-level-errors="validationErrors[name]"
                @cleared="clearInvalidMedia()"
            />

            <component
                :is="sortable ? 'draggable' : 'div'"
                :list="state.media"
                v-show="state.media && state.media.length"
                class="media-library-items"
                handle=".dragula-handle"
                @update="handleSortEnd"
            >
                <div
                    v-for="object in state.media"
                    class="media-library-item media-library-item-row"
                    :data-media-library-uuid="object.attributes.uuid"
                >
                    <div v-if="sortable" class="dragula-handle media-library-row-drag">
                        <icon v-if="state.media.length" icon="drag" />
                    </div>

                    <thumb
                        :uploadInfo="object.upload"
                        :validation-rules="validationRules"
                        :img-props="getImgProps(object)"
                        @replaced="replaceMedia(object, $event)"
                    />

                    <item-errors
                        v-if="getErrors(object).length"
                        :object-errors="getErrors(object)"
                        @back="clearObjectErrors(object)"
                    />

                    <template v-else>
                        <slot name="properties" :object="object">
                            <div class="media-library-properties media-library-properties-fixed">
                                <div v-if="object.attributes.extension" class="media-library-property">
                                    {{ object.attributes.extension.toUpperCase() }}
                                </div>

                                <div v-if="object.attributes.size" class="media-library-property">
                                    {{ (object.attributes.size / 1024).toFixed(2) }} KB
                                </div>

                                <div v-if="object.attributes.original_url" class="media-library-property">
                                    <a
                                        :href="object.attributes.original_url"
                                        download
                                        target="_blank"
                                        class="media-library-text-link"
                                    >
                                        {{ window.mediaLibraryTranslations.download }}
                                    </a>
                                </div>
                            </div>
                        </slot>

                        <slot
                            name="fields"
                            :object="object"
                            :getCustomPropertyInputProps="
                                (propertyName) => getCustomPropertyInputProps(object, propertyName)
                            "
                            :getCustomPropertyInputListeners="
                                (propertyName) => getCustomPropertyInputListeners(object, propertyName)
                            "
                            :getCustomPropertyInputErrors="
                                (propertyName) => getCustomPropertyInputErrors(object, propertyName)
                            "
                            :getNameInputProps="() => getNameInputProps(object)"
                            :getNameInputListeners="() => getNameInputListeners(object)"
                            :getNameInputErrors="() => getNameInputErrors(object)"
                        >
                            <div class="media-library-properties">
                                <div class="media-library-field">
                                    <label class="media-library-label">
                                        {{ window.mediaLibraryTranslations.name }}
                                    </label>
                                    <input
                                        class="media-library-input"
                                        v-bind="getNameInputProps(object)"
                                        v-on="getNameInputListeners(object)"
                                        dusk="media-library-field-name"
                                    />

                                    <p v-for="error in getNameInputErrors(object)" class="media-library-field-error">
                                        {{ error }}
                                    </p>
                                </div>
                            </div>
                        </slot>
                    </template>

                    <div class="media-library-row-remove" @click.stop="removeMedia(object)" dusk="remove">
                        <icon icon="remove" />
                    </div>
                </div>
            </component>

            <hidden-fields :name="name" :media-state="state.media" />

            <div v-show="!computedMaxItems || state.media.length < computedMaxItems" class="media-library-uploader">
                <uploader
                    :multiple="multiple"
                    v-bind="{ ...getDropZoneProps(), ...getFileInputProps() }"
                    v-on="{ ...getDropZoneListeners(), ...getFileInputListeners() }"
                    add
                    :file-type-help-text="fileTypeHelpText"
                />
            </div>
        </div>
    </media-library-renderless>
</template>

<script>
import { VueDraggableNext } from 'vue-draggable-next';
import {
    MediaLibraryRenderless,
    HiddenFields,
    DropZone,
    ListErrors,
    ItemErrors,
    Icons,
    Icon,
    Thumb,
    Uploader,
} from '@spatie/media-library-pro-vue3';

export default {
    props: {
        name: { required: false, type: String },
        initialValue: { required: false, type: [Array, Object] },
        validationErrors: { default: () => ({}), type: [Object, Array] },
        routePrefix: { required: false, type: String },
        translations: { default: () => {}, type: Object },
        validationRules: { required: false, type: Object },
        multiple: { default: true, type: Boolean },
        sortable: { default: true, type: Boolean },
        maxItems: { required: false, type: Number },
        maxSizeForPreviewInBytes: { required: false, type: Number },
        vapor: { required: false, type: Boolean },
        vaporSignedStorageUrl: { required: false, type: String },
        uploadDomain: { required: false, type: String },
        withCredentials: { required: false, type: Boolean },
        headers: { required: false, type: Object },
        fileTypeHelpText: { required: false, type: String },
        beforeUpload: { default: () => {}, type: Function },
        afterUpload: { default: () => {}, type: Function },
    },

    emits: [
        'change',
        'is-ready-to-submit-change',
        'has-uploads-in-progress-change',
        'isReadyToSubmitChange',
        'hasUploadsInProgressChange',
    ],

    components: {
        draggable: VueDraggableNext,
        MediaLibraryRenderless,
        HiddenFields,
        DropZone,
        ListErrors,
        ItemErrors,
        Icons,
        Icon,
        Thumb,
        Uploader,
    },

    data: () => ({
        mediaLibrary: null,
        window,
    }),

    computed: {
        computedMaxItems() {
            return this.multiple ? this.maxItems : 1;
        },
    },

    mounted() {
        this.mediaLibrary = this.$refs.mediaLibraryRenderless.mediaLibrary;
    },

    methods: {
        handleSortEnd(event) {
            this.$refs.mediaLibraryRenderless.setOrder(
                Array.from(event.from.children || []).map((element) => {
                    return element.getAttribute('data-media-library-uuid');
                }),
                false
            );
        },
    },
};
</script>
