// payload/modules/medialibrarypro/resources/js/media-library-pro-react/src/DropZone.tsx
import * as React from 'react';
import { getFileTypeIsAllowed } from '@spatie/media-library-pro-core';
import { MediaLibrary } from '@spatie/media-library-pro-core/dist/types';

type Props = {
    validationAccept?: MediaLibrary.Config['validationRules']['accept'];
    children: ({
        hasDragObject,
        isDropTarget,
    }: {
        hasDragObject: boolean;
        isDropTarget: boolean;
        isValid: boolean;
    }) => React.ReactNode;
    onDrop: (event: React.DragEvent<HTMLDivElement>) => void;
} & React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>;

export default function DropZone({ validationAccept, children, onDrop, ...props }: Props) {
    const dropZoneRef = React.useRef<null | HTMLDivElement>(null);

    const [hasDragObject, setHasDragObject] = React.useState(false);
    const [isDropTarget, setIsDropTarget] = React.useState(false);
    const [isValid, setIsValid] = React.useState(true);

    const dragCounter = React.useRef(0);

    function handleDocumentDragenter(e: DragEvent) {
        e.preventDefault();

        dragCounter.current++;

        testIfValid(e);

        setHasDragObject(true);
    }

    function handleDocumentDragleave(e: DragEvent) {
        e.preventDefault();

        dragCounter.current--;

        if (dragCounter.current === 0) {
            setHasDragObject(false);
        }
    }

    function handleDocumentDrop(e: DragEvent) {
        e.preventDefault();

        dragCounter.current = 0;

        setHasDragObject(false);
    }

    function handleDocumentDragOver(e: DragEvent) {
        e.preventDefault();

        const overElement = dropZoneRef.current?.contains(e.target as any);

        if (!overElement) {
            return setIsDropTarget(false);
        }

        setIsDropTarget(true);
    }

    function handleDrop(e: React.DragEvent<HTMLDivElement>) {
        e.preventDefault();

        if (e.dataTransfer.files.length) {
            onDrop(e);
        }

        dragCounter.current = 0;

        setHasDragObject(false);
        setIsDropTarget(false);
    }

    React.useEffect(() => {
        document.addEventListener('dragenter', handleDocumentDragenter);
        document.addEventListener('dragleave', handleDocumentDragleave);
        document.addEventListener('dragover', handleDocumentDragOver);
        document.addEventListener('drop', handleDocumentDrop);

        return () => {
            document.removeEventListener('dragenter', handleDocumentDragenter);
            document.removeEventListener('dragleave', handleDocumentDragleave);
            document.removeEventListener('dragover', handleDocumentDragOver);
            document.removeEventListener('drop', handleDocumentDrop);
        };
    }, []);

    function testIfValid(e: DragEvent) {
        if (!e.dataTransfer) {
            return;
        }

        if (!e.dataTransfer.items || !e.dataTransfer.items.length) {
            return setIsValid(true);
        }

        if (!validationAccept || !validationAccept.length) {
            return setIsValid(true);
        }

        setIsValid(
            Array.from(e.dataTransfer.items).every((item) => {
                return getFileTypeIsAllowed(item.type, validationAccept);
            })
        );
    }

    return (
        <div ref={dropZoneRef} onDrop={handleDrop} {...props}>
            {children({ hasDragObject, isDropTarget, isValid })}
        </div>
    );
}

// payload/modules/medialibrarypro/resources/js/media-library-pro-vue3/src/DropZone.vue
<template>
    <div v-bind="$attrs" @drop="handleDrop" @click.stop="$emit('clicked')">
        <slot v-bind="$data"></slot>
    </div>
</template>

<script>
import { getFileTypeIsAllowed } from '@spatie/media-library-pro-core';

export default {
    props: {
        validationAccept: { default: () => [], type: Array },
    },

    emits: ['clicked', 'dropped'],

    data: () => ({
        hasDragObject: false,
        isDropTarget: false,
        isValid: true,
    }),

    mounted() {
        document.addEventListener('dragenter', this.handleDocumentDragenter);
        document.addEventListener('dragleave', this.handleDocumentDragleave);
        document.addEventListener('dragover', this.handleDocumentDragOver);
        document.addEventListener('drop', this.handleDocumentDrop);
    },

    beforeUnmount() {
        document.removeEventListener('dragenter', this.handleDocumentDragenter);
        document.removeEventListener('dragleave', this.handleDocumentDragleave);
        document.removeEventListener('dragover', this.handleDocumentDragOver);
        document.removeEventListener('drop', this.handleDocumentDrop);
    },

    methods: {
        handleDocumentDragenter(e) {
            e.preventDefault();

            if (e.dataTransfer.dropEffect === 'move') {
                return;
            }

            this.testIfValid(e);

            this.hasDragObject = true;
        },

        handleDocumentDragleave(e) {
            if (!e.clientX && !e.clientY) {
                e.preventDefault();

                this.hasDragObject = false;
            }
        },

        handleDocumentDrop(e) {
            e.preventDefault();

            this.hasDragObject = false;
        },

        handleDocumentDragOver(e) {
            e.preventDefault();

            const overElement = this.$el.contains(e.target);

            if (!overElement) {
                return (this.isDropTarget = false);
            }

            this.isDropTarget = true;
        },

        handleDrop(e) {
            e.preventDefault();

            if (e.dataTransfer.files.length) {
                this.$emit('dropped', e);
            }

            this.hasDragObject = false;
            this.isDropTarget = false;
        },

        testIfValid(e) {
            if (!e.dataTransfer.items || !e.dataTransfer.items.length) {
                return (this.isValid = true);
            }

            if (!this.validationAccept || !this.validationAccept.length) {
                return (this.isValid = true);
            }

            this.isValid = Array.from(e.dataTransfer.items).every((item) => {
                return getFileTypeIsAllowed(item.type, this.validationAccept);
            });
        },
    },
};
</script>
