// payload/modules/medialibrarypro/resources/js/media-library-pro-react/src/HiddenFields.tsx
import * as React from 'react';
import { MediaLibrary } from '@spatie/media-library-pro-core/dist/types';
import { sanitizeForInput, getObjPaths } from '@spatie/media-library-pro-core';
import get from 'lodash/get';

type Props = {
    name: string;
    mediaState: MediaLibrary.State['media'];
};

export default function HiddenFields({ name, mediaState }: Props) {
    return (
        <>
            {mediaState.map((object) => {
                return getObjPaths(object.attributes).map((parameterName) => (
                    <input
                        key={parameterName}
                        name={`${name}[${object.attributes.uuid}]${parameterName}`}
                        defaultValue={sanitizeForInput(get(object.attributes, parameterName))}
                        type="hidden"
                    />
                ));
            })}
        </>
    );
}

// payload/modules/medialibrarypro/resources/js/media-library-pro-vue3/src/HiddenFields.vue
<template>
    <div style="display: none">
        <template v-for="object in mediaState">
            <template v-for="parameterName in getObjPaths(object.attributes)">
                <input
                    :name="`${name}[${object.attributes.uuid}]${parameterName}`"
                    :value="sanitizeForInput(get(object.attributes, parameterName))"
                    type="hidden"
                />
            </template>
        </template>
    </div>
</template>

<script>
import { sanitizeForInput, getObjPaths } from '@spatie/media-library-pro-core';
import get from 'lodash/get';

export default {
    props: {
        name: { required: true, type: String },
        mediaState: { default: () => [], type: Array },
    },

    methods: {
        getObjPaths,
        sanitizeForInput,
        get,
    },
};
</script>
