// payload/modules/medialibrarypro/resources/js/media-library-pro-react/src/ItemErrors.tsx
import * as React from 'react';

type Props = {
    objectErrors: string[];
    onBack?: (e: React.MouseEvent) => void;
};

export default function ItemErrors({ objectErrors, onBack }: Props) {
    return (
        <>
            {objectErrors.length > 0 && (
                <div className="media-library-properties">
                    <span className="media-library-text-error">
                        {objectErrors.map((error) => (
                            <span key={error}>{error}</span>
                        ))}
                    </span>
                    <a
                        className="media-library-text-link media-library-text-error media-library-help-clear"
                        onClick={onBack}
                    >
                        {window.mediaLibraryTranslations.goBack}
                    </a>
                </div>
            )}
        </>
    );
}

// payload/modules/medialibrarypro/resources/js/media-library-pro-vue2/src/ItemErrors.vue
<template>
    <div v-if="objectErrors.length > 0" class="media-library-properties">
        <span class="media-library-text-error">
            <span v-for="error in objectErrors" :key="error">{{ error }}</span>
        </span>
        <a
            class="media-library-text-link media-library-text-error media-library-help-clear"
            @click.stop="$emit('back')"
        >
            {{ window.mediaLibraryTranslations.goBack }}
        </a>
    </div>
</template>

<script>
export default {
    props: {
        objectErrors: { required: true, type: Array },
    },

    data: () => ({ window }),

    emits: ['back'],
};
</script>
